version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password12345
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password12345
    depends_on:
      - mongo

  shopping-cart-api:
    container_name: shopping-cart-api
    build:
        context: .
        dockerfile: ShoppingCart.API/Dockerfile
    restart: always
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8001"
      -ConnectionString: ${APP_MONGODB_CONNECTION:-mongodb://root:Password12345@localhost:27017}
      -DatabaseName: ${APP_MONGODB:-ShoppingDB}
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    depends_on:
      - mongo